name: urlshort CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./project

    steps:
    - uses: actions/checkout@v4
    - name: Setting Up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Installing Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Pytest for APIs
      run: |
        pytest